ODE_SDC_HOME := ../..

PRECISION  = DOUBLE
PROFILE    = FALSE

DEBUG      = FALSE

DIM        = 1

COMP	   = gnu

USE_MPI    = FALSE
USE_CUDA   = FALSE

Bpack   := ./Make.package
Blocs   := .

include $(ODE_SDC_HOME)/Make.sdc

